# Generated by Django 3.2.9 on 2021-11-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('balance', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='DealPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deal_positions',
            },
        ),
        migrations.CreateModel(
            name='Deal2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.account')),
                ('deal_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.dealposition')),
            ],
            options={
                'db_table': 'deals2021',
            },
        ),
        migrations.CreateModel(
            name='Deal2020',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.account')),
                ('deal_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.dealposition')),
            ],
            options={
                'db_table': 'deals2020',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddIndex(
            model_name='deal2021',
            index=models.Index(fields=['created_at'], name='deals2021_created_151616_idx'),
        ),
        migrations.AddIndex(
            model_name='deal2020',
            index=models.Index(fields=['created_at'], name='deals2020_created_bee250_idx'),
        ),
    ]
